name: Process Waitlist Submission

on:
  repository_dispatch:
    types: [waitlist_submission]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.WAITLIST_TOKEN }}
          REPO: ${{ secrets.WAITLIST_REPO }}
        run: |
          gh issue create \
            --title "New Waitlist Submission - $(date +%Y-%m-%d)" \
            --body "Name: ${{ github.event.client_payload.data.name }}\nEmail: ${{ github.event.client_payload.data.email }}\nPhone: ${{ github.event.client_payload.data.phone }}" \
            --repo $REPO 